"""Register a training run executed outside algoforge (e.g. a Colab notebook generated by
scripts/generate_colab_notebook.py) as a completed TrainingRun.

Runs independently of the backend/Celery processes — connects to Postgres directly, so it's
safe to use while other jobs are active. See model/service.py:import_external_training_run.

Usage (from algoforge/backend):
    python -m scripts.import_training_run --model-id 12 --dataset-id 3 \\
        --checkpoint best.pt --metadata metrics.json \\
        [--notebook-url https://colab.research.google.com/...]
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent.parent / ".env")
except ImportError:
    pass


class _FileUpload:
    """Minimal stand-in for fastapi.UploadFile. import_external_training_run only calls
    .filename and `await .read(n)`, both satisfied here directly against a local file — so the
    same service code path runs from this offline CLI as from the HTTP import endpoint."""

    def __init__(self, path: Path):
        self.filename = path.name
        self._fh = path.open("rb")

    async def read(self, n: int) -> bytes:
        return self._fh.read(n)


async def _run(model_id: int, dataset_id: int, checkpoint_path: Path, metadata: dict) -> None:
    from database import async_session_factory
    from model.models import TrainingRunImportCreate
    from model.service import model_service

    metadata.setdefault("dataset_id", dataset_id)
    payload = TrainingRunImportCreate.model_validate(metadata)

    async with async_session_factory() as db:
        upload = _FileUpload(checkpoint_path)
        run = await model_service.import_external_training_run(db, model_id, upload, payload)
        await db.commit()
        print(f"Registered TrainingRun {run.id} (model {model_id}, source=external)")
        print(f"  best_epoch:    {run.best_epoch}")
        print(f"  val_loss:      {run.val_loss}")
        print(f"  artifact_path: {run.artifact_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--model-id", type=int, required=True)
    parser.add_argument("--dataset-id", type=int, required=True, help="The algoforge dataset the snapshot was taken from")
    parser.add_argument("--checkpoint", required=True, help="Path to the downloaded best.pt")
    parser.add_argument("--metadata", required=True, help="Path to the downloaded metrics.json")
    parser.add_argument("--notebook-url", help="Colab/GitHub URL of the notebook that produced this run")
    args = parser.parse_args()

    metadata = json.loads(Path(args.metadata).read_text())
    if args.notebook_url:
        metadata.setdefault("external_ref", {})["notebook_url"] = args.notebook_url

    asyncio.run(_run(args.model_id, args.dataset_id, Path(args.checkpoint), metadata))


if __name__ == "__main__":
    main()
